language: python
python:
- '2.7'
- '3.6'
script: python setup.py install
deploy:
  provider: pypi
  user: wuyue
  password:
    secure: 7sJA2nimxQQLdm6iifp0cC2ccDj+rPdzRPVB9BlNQV03G7ev37eXC3D2BWZcUyCUhUrIPFRlYuAxrcq6XlKJ9+0vQH8XhWpaMQhxcU2Zca8+AVFZ3yWrPihRGGWOvBpNQ25d5dc9SPMQIvzJdnVTgkbxQf3kvEk3rSSKfPWScKZZWYWUf2btunRzJSC24O6BvcbU9XW7dgXTUR7wb5P1JDFsQ3+U4DK7X+HEGq4TO1rYobEEw9Bnf8RGQuR1L64vusza3TDTag3D5yQ3iC8rX9GLxLQGlVnVlTUuj1jfw78m6jSQgNDB7Eyt3Nk9kbSDlSeed/uD+aWSDm8jh/RinZ0/OBq/yUz7/hkermvevZgnGQq36TH5L1xzlphAIO39gLL0RtEPYLw24jUmE+fRK8C5g2YLpVaV4JKqtrh2qNKjbCXXSXYXIN2cdkjRCXAEfs6bOhhrV1JecOwseIfG+gQLzY/WSUU0OCNnPZo21kl4kKH45hI96QwXLM6PPfk69JWE3DIPTB5F/Nht5YZfi66Ni9a/0LLew4qKaGBk19UvguMAfU8LonN/m+REoNJRGdaaSPq6BH224NtqnnFm/brqfQ/ZZCFXCaRoNPUip2k2wShfkH6LjG5BYsm3V83xJikFphrgNFHRuY3mFe6bA6SedvJvLH2/LpV28vbRh1A=
  skip_existing: true
  skip_cleanup: true
  on:
    tag: true
    all_branches: true

branches:
  except:
  - develop
  - master
